### ISSUE TITLE
unknown buttons on mobile device

### ISSUE THREAD

**Issue by leez79** [JeremyHeleine/Photo-Sphere-Viewer#14]
![2015-11-05 11 36 53](https://cloud.githubusercontent.com/assets/11968029/10978034/f725f9b8-83b1-11e5-949d-943a120e1585.png)

Hi Jeremy, I opened a sphere image on my mobile device (Galaxy Note 4) and found two unknown buttons. Can you please explain what they are? I cannot see the buttons on Chrome developer tools' simulation screen, but they appear on my actual phone. Thanks!

**Comment by JeremyHeleine** [comment]
Hi,

These buttons are here since this summer. The button on the right is here to enable / disable the use of the gyroscope: when this option is activated, you just have to rotate your device to navigate in the panorama. The button on the left is for activating / deactivating the VR feature: you put your smartphone in a VR headset like the Google Cardboard and you are teleported into the scene. ;)

It's natural you don't see these buttons on a computer. They appear only on devices that allow the use of the gyroscope (smartphone or tablet for example).

Don't hesitate to click on them to test them, they won't break your phone! :P
