### ISSUE TITLE
ZoomIn and ZoomOut tweaking

### ISSUE THREAD

**Issue by ner00** [JeremyHeleine/Photo-Sphere-Viewer#38]
Hi

Would someone please tell me how the ZoomIn or ZoomOut speed/amount can be changed?
I have tried changing the values in _PhotoSphereViewer.js_:

``` javascript
    this.zoomIn = function() {
        if (zoom_lvl < 100)
            zoom(zoom_lvl + 10);
    };
```

This was pointless...
I also tried the same thing in _photo-sphere-viewer.min.js_:

``` javascript
    this.zoomIn=function(){100>he&&D(he+10)}
```

None of those worked, it still keeps the default zoom increase/decrease speed/amount using the mouse wheel. The README doesn't seem to address this or I failed to figure that out. I appreciate the help.

Thank you.

**Comment by ner00** [comment]
I found a dirty way to achieve this.

In *PhotoSphereViewer.js*, *onMouseWheel = function(evt)*
```javascript
      if (direction > 0)
        zoom_lvl = zoom_lvl + 10;
      else
        zoom_lvl = zoom_lvl - 10;
```

In *photo-sphere-viewer.min.js*, *O=function(e)*
```javascript
if(o>0)he=he+10;else he=he-10;
```

If anyone has a better suggestion, I'm all ears.

**Comment by JeremyHeleine** [comment]
Hi,

Sorry for the delay. Currently there's no option to change the zoom speed, but it's a good idea. I'll add this option.

As an explanation, `onMouseWheel()` is called when you zoom with your mouse. The functions you modified before (`zoomIn()` and `zoomOut()`) are called when you use the buttons in the navigation bar. That's why you didn't notice any change if you didn't try the buttons.

**Comment by JeremyHeleine** [comment]
The new `zoom_speed` option now allows this change.
