### ISSUE TITLE
cross-domain

### ISSUE THREAD

**Issue by xiaodel** [JeremyHeleine/Photo-Sphere-Viewer#89]
Failed to load https://lezf-rent.oss-cn-shanghai.aliyuncs.com/rent/vr/default/1.jpg: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:7070' is therefore not allowed access.

**Comment by canado** [comment]
In order to fix this, you need to add headers to the server
The quickest option is to try to add headers with .htaccess

```
<ifmodule mod_headers.c="">
Header add Access-Control-Allow-Origin "*"
Header add Access-Control-Allow-Headers "origin, x-requested-with, content-type"
Header add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"
</ifmodule>
```

If this is not working you can try to setup new configuration with apache or nginx 

Also note that sometimes after header are in place, you just need to rename the picture name to force a new cache on the file

**Comment by xiaodel** [comment]
Ok, I'll try
